2016-02-19 16:42:37,904 [29] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:列名 'null,null,null' 无效。
列名 'null,null,null' 无效。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-19 16:44:01,182 [8] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:列名 'null,null,null' 无效。
列名 'null,null,null' 无效。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-19 16:45:17,112 [29] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:列名 '7606406666,7606406701,7606406701' 无效。
列名 '"7606406668","7606406706","7606406706"' 无效。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-19 16:50:50,415 [10] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:列名 '7606406666,7606406701,7606406701' 无效。
列名 '"7606406668","7606406706","7606406706"' 无效。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-19 16:52:13,974 [10] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:列名 '7606406666,7606406701,7606406701' 无效。
列名 '"7606406668","7606406706","7606406706"' 无效。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-19 16:53:16,683 [21] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:列名 '7606406666,7606406701,7606406701' 无效。
列名 '"7606406668","7606406706","7606406706"' 无效。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
