2016-02-20 09:45:41,233 [16] ERROR 引发异常的方法：System.Web.Mvc.ActionResult addToShoppingCart(System.String, System.String, System.String)
错误信息：Object reference not set to an instance of an object.
错误堆栈：   at HKTHMall.Web.Areas.Money.Controllers.ShoppingCartController.addToShoppingCart(String strGoodsIds, String strSkuNumber, String strCount) in f:\WorkSpace\src\HKTHMall.Web\Areas\Money\Controllers\ShoppingCartController.cs:line 88
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
错误发生地址：/money/ShoppingCart/addToShoppingCart
 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 09:45:46,323 [17] ERROR 引发异常的方法：System.Web.Mvc.ActionResult addToShoppingCart(System.String, System.String, System.String)
错误信息：Object reference not set to an instance of an object.
错误堆栈：   at HKTHMall.Web.Areas.Money.Controllers.ShoppingCartController.addToShoppingCart(String strGoodsIds, String strSkuNumber, String strCount) in f:\WorkSpace\src\HKTHMall.Web\Areas\Money\Controllers\ShoppingCartController.cs:line 88
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
错误发生地址：/money/ShoppingCart/addToShoppingCart
 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 09:45:49,614 [16] ERROR 引发异常的方法：System.Web.Mvc.ActionResult addToShoppingCart(System.String, System.String, System.String)
错误信息：Object reference not set to an instance of an object.
错误堆栈：   at HKTHMall.Web.Areas.Money.Controllers.ShoppingCartController.addToShoppingCart(String strGoodsIds, String strSkuNumber, String strCount) in f:\WorkSpace\src\HKTHMall.Web\Areas\Money\Controllers\ShoppingCartController.cs:line 88
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
错误发生地址：/money/ShoppingCart/addToShoppingCart
 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 14:45:10,672 [21] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:')' 附近有语法错误。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 14:48:43,094 [15] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:')' 附近有语法错误。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 14:51:56,882 [28] ERROR 类名:HKTHMall.Services.Products.ProductService	 方法:GetProductListByPrdouctId	 错误信息:')' 附近有语法错误。 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 16:43:34,288 [17] ERROR *****************初始化订单消息队列成功 ****************** - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 16:43:34,318 [17] ERROR 订单编号【7529245255】已加入订单处理队列 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 17:27:43,015 [19] ERROR *****************初始化订单消息队列成功 ****************** - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
2016-02-20 17:27:43,100 [19] ERROR 订单编号【7529245286】已加入订单处理队列 - [f:\WorkSpace\src\Framework\BrCms.Framework\Logging\Logger.cs:26]
