//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Department
    {
        public AC_Department()
        {
            this.AC_User = new HashSet<AC_User>();
        }
    
        public int ID { get; set; }
        public string DeptName { get; set; }
        public int ParentID { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    
        public virtual ICollection<AC_User> AC_User { get; set; }
    }
}
