//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_OperateLog
    {
        public long OperateID { get; set; }
        public string OperateName { get; set; }
        public long UserID { get; set; }
        public System.DateTime OperateTime { get; set; }
        public string OperateContent { get; set; }
        public string Remark { get; set; }
        public string IP { get; set; }
    }
}
