//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Role
    {
        public AC_Role()
        {
            this.AC_User = new HashSet<AC_User>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleModuleValue { get; set; }
        public string RoleFuctionValue { get; set; }
        public string RoleDescription { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDT { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
    
        public virtual ICollection<AC_User> AC_User { get; set; }
    }
}
