//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_NewsInfo
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int TypeID { get; set; }
        public string NewsContent { get; set; }
        public string Releaser { get; set; }
        public long AcUserID { get; set; }
        public long UserID { get; set; }
        public Nullable<System.DateTime> ReleaseDT { get; set; }
        public int IsCheck { get; set; }
        public Nullable<int> SendStatus { get; set; }
        public int IsDelete { get; set; }
        public int IsPic { get; set; }
        public string PicPath { get; set; }
        public int IsHasNaviContent { get; set; }
        public string NaviContent { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    }
}
