//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Brand_Lang = new HashSet<Brand_Lang>();
        }
    
        public int BrandID { get; set; }
        public string BrandUrl { get; set; }
        public string Remark { get; set; }
        public int BrandState { get; set; }
        public string AddUsers { get; set; }
        public System.DateTime AddTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public string FirstPY { get; set; }
    
        public virtual ICollection<Brand_Lang> Brand_Lang { get; set; }
    }
}
