//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryId { get; set; }
        public int parentId { get; set; }
        public string IconCode { get; set; }
        public string BackColor { get; set; }
        public string AddUser { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<bool> AuditState { get; set; }
        public long Place { get; set; }
        public int Grade { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    }
}
