//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public string ComplaintsID { get; set; }
        public string OrderID { get; set; }
        public long MerchantID { get; set; }
        public long UserID { get; set; }
        public int complainType { get; set; }
        public string Content { get; set; }
        public System.DateTime ComplaintsDate { get; set; }
        public string DealPeople { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public int Flag { get; set; }
        public string Comments { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
