//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MsgId { get; set; }
        public string MsgPerson { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string MsgContent { get; set; }
        public System.DateTime CreateDT { get; set; }
    }
}
