//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTrackingLog
    {
        public long OrderTrackingId { get; set; }
        public string OrderID { get; set; }
        public int OrderStatus { get; set; }
        public string TrackingContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
