//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Complaints = new HashSet<Complaints>();
            this.OrderAddress = new HashSet<OrderAddress>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.OrderTrackingLog = new HashSet<OrderTrackingLog>();
            this.RecommendBonusRecord = new HashSet<RecommendBonusRecord>();
            this.ReturnProductInfo = new HashSet<ReturnProductInfo>();
        }
    
        public string OrderID { get; set; }
        public long UserID { get; set; }
        public long MerchantID { get; set; }
        public int OrderStatus { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal CostAmount { get; set; }
        public int PayChannel { get; set; }
        public int PayType { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public decimal Vouchers { get; set; }
        public decimal ExpressMoney { get; set; }
        public int OrderSource { get; set; }
        public int PayDays { get; set; }
        public int DelayDays { get; set; }
        public string MerchantRemark { get; set; }
        public string Remark { get; set; }
        public int IsDisplay { get; set; }
        public int IsReward { get; set; }
        public int ComplaintStatus { get; set; }
        public int RefundFlag { get; set; }
        public Nullable<int> IsPurchase { get; set; }
        public Nullable<int> ExpressID { get; set; }
        public string ExpressOrder { get; set; }
    
        public virtual ICollection<Complaints> Complaints { get; set; }
        public virtual ICollection<OrderAddress> OrderAddress { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<OrderTrackingLog> OrderTrackingLog { get; set; }
        public virtual ICollection<RecommendBonusRecord> RecommendBonusRecord { get; set; }
        public virtual ICollection<ReturnProductInfo> ReturnProductInfo { get; set; }
    }
}
