//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOrder
    {
        public string PaymentOrderID { get; set; }
        public long UserID { get; set; }
        public decimal ProductAmount { get; set; }
        public decimal RealAmount { get; set; }
        public int Flag { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public int PayType { get; set; }
        public int PayChannel { get; set; }
        public string outOrderId { get; set; }
    }
}
