//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public long ProductImageId { get; set; }
        public string ProductName { get; set; }
        public string ImageUrl { get; set; }
        public int ImageType { get; set; }
        public string linkUrl { get; set; }
        public long place { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDT { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    }
}
