//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRule
    {
        public long ProductRuleId { get; set; }
        public long ProductId { get; set; }
        public int SalesRuleId { get; set; }
        public string PrdoctRuleName { get; set; }
        public int BuyQty { get; set; }
        public int SendQty { get; set; }
        public decimal Discount { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StarDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesRule SalesRule { get; set; }
    }
}
