//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public string PurchaseOrderId { get; set; }
        public string OrderID { get; set; }
        public long SupplierId { get; set; }
        public decimal PurchaseAmount { get; set; }
        public decimal RealPurchaseAmount { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Deliveryer { get; set; }
        public Nullable<int> status { get; set; }
    }
}
