//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendBonusRecord
    {
        public long RecommendBonusRecordId { get; set; }
        public string OrderID { get; set; }
        public decimal OrderAmount { get; set; }
        public long ConsumerID { get; set; }
        public long ReferrerID { get; set; }
        public int RewardType { get; set; }
        public decimal RewardRate { get; set; }
        public decimal RewardAmount { get; set; }
        public System.DateTime RewardDT { get; set; }
        public int RewardSource { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
