//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public long ReportId { get; set; }
        public long ReportUserId { get; set; }
        public long BeReporteId { get; set; }
        public int ReportTypeId { get; set; }
        public string ReportContent { get; set; }
        public System.DateTime CreateDT { get; set; }
        public int Status { get; set; }
        public string Result { get; set; }
        public string DealUser { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
    }
}
