//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnProductInfo
    {
        public string ReturnOrderID { get; set; }
        public long UserID { get; set; }
        public string OrderID { get; set; }
        public long ProductId { get; set; }
        public Nullable<int> ProductSnapshotID { get; set; }
        public decimal TradeAmount { get; set; }
        public decimal RefundAmount { get; set; }
        public int ReturntNumber { get; set; }
        public int ReasonType { get; set; }
        public string Discription { get; set; }
        public int ReturnType { get; set; }
        public string ReturnAddress { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverMobile { get; set; }
        public string ReceiverTel { get; set; }
        public int ReturnStatus { get; set; }
        public string MerchantReturnAddress { get; set; }
        public string ReturnText { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string AuditUser { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string RefundPerson { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public long OrderDetailsID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
