//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public long ShoppingCartId { get; set; }
        public long ProductID { get; set; }
        public long SKU_ProducId { get; set; }
        public long UserID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CartDate { get; set; }
        public int IsCheck { get; set; }
    
        public virtual YH_User YH_User { get; set; }
    }
}
