//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU_Product
    {
        public long SKU_ProducId { get; set; }
        public long ProductId { get; set; }
        public string SKUStr { get; set; }
        public string ProductCode { get; set; }
        public string SkuName { get; set; }
        public int Stock { get; set; }
        public decimal HKPrice { get; set; }
        public decimal MarketPrice { get; set; }
        public decimal PurchasePrice { get; set; }
        public int IsUse { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
