//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU_AttributeValues
    {
        public long ValueId { get; set; }
        public long AttributeId { get; set; }
        public int DisplaySequence { get; set; }
        public string ValueStr { get; set; }
        public string ImageUrl { get; set; }
        public string ValuesGroup { get; set; }
    
        public virtual SKU_Attributes SKU_Attributes { get; set; }
    }
}
