//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU_Attributes
    {
        public SKU_Attributes()
        {
            this.SKU_AttributeValues = new HashSet<SKU_AttributeValues>();
            this.SKU_ProductTypeAttribute = new HashSet<SKU_ProductTypeAttribute>();
        }
    
        public long AttributeId { get; set; }
        public string AttributeName { get; set; }
        public int AttributeType { get; set; }
        public int IsSKU { get; set; }
        public int UsageMode { get; set; }
        public int IsSearch { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    
        public virtual ICollection<SKU_AttributeValues> SKU_AttributeValues { get; set; }
        public virtual ICollection<SKU_ProductTypeAttribute> SKU_ProductTypeAttribute { get; set; }
    }
}
