//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public long SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int THAreaID { get; set; }
        public string Address { get; set; }
        public string LinkMan { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    }
}
