//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YF_FareTemplateAreaGroup
    {
        public int FareTemplateAreaGroupID { get; set; }
        public int FareTemplateID { get; set; }
        public int FirstQuantity { get; set; }
        public decimal FirstBillingPrice { get; set; }
        public int ContinueQuantity { get; set; }
        public decimal ContinueBillingPrice { get; set; }
        public decimal InsufficientPrice { get; set; }
        public decimal Freight { get; set; }
        public string AreaNames { get; set; }
        public int IsDefault { get; set; }
    }
}
