//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YH_UserVerify
    {
        public int ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string UserIP { get; set; }
        public string VerifyCode { get; set; }
        public System.DateTime VerfyTime { get; set; }
        public int IsUse { get; set; }
        public string Phone { get; set; }
        public int VerfyType { get; set; }
        public System.DateTime SendTime { get; set; }
    }
}
