//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YH_UserFeedBack
    {
        public int ID { get; set; }
        public string TypeIDList { get; set; }
        public int LevelNum { get; set; }
        public string Remark { get; set; }
        public string Account { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Result { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    }
}
