//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YH_UserBankAccount
    {
        public int ID { get; set; }
        public long UserID { get; set; }
        public int BankID { get; set; }
        public int IsDefault { get; set; }
        public string BankSubbranch { get; set; }
        public string BankAddress { get; set; }
        public string BankUserName { get; set; }
        public string BankAccount { get; set; }
        public int IsUse { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
    
        public virtual YH_User YH_User { get; set; }
    }
}
