//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZJ_RechargeOrder
    {
        public string OrderNO { get; set; }
        public long UserID { get; set; }
        public int RechargeChannel { get; set; }
        public decimal RechargeAmount { get; set; }
        public Nullable<System.DateTime> RechargeDT { get; set; }
        public byte RechargeResult { get; set; }
        public System.DateTime CreateDT { get; set; }
        public int IsDisplay { get; set; }
        public byte OrderSource { get; set; }
    }
}
