//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZJ_RebateInfo
    {
        public long ID { get; set; }
        public string OrderID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> SKUID { get; set; }
        public Nullable<long> OrderDetailsID { get; set; }
        public decimal TotalMoney { get; set; }
        public int TotalDay { get; set; }
        public decimal PaidMoney { get; set; }
        public int PaidDays { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string CreateBY { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdateBY { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string Remark { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual YH_User YH_User { get; set; }
    }
}
