//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZJ_Rebate
    {
        public long ID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public long ProductId { get; set; }
        public Nullable<int> RebateDays { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ResidualAmount { get; set; }
        public Nullable<decimal> RebateAmount { get; set; }
        public Nullable<int> RebateDay { get; set; }
        public Nullable<int> RebateStatus { get; set; }
        public Nullable<long> RebateUserID { get; set; }
        public string CreateBY { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBY { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> StarteTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
