//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZJ_UserBalanceChangeLog
    {
        public int ID { get; set; }
        public long UserID { get; set; }
        public decimal AddOrCutAmount { get; set; }
        public int IsAddOrCut { get; set; }
        public decimal OldAmount { get; set; }
        public decimal NewAmount { get; set; }
        public int AddOrCutType { get; set; }
        public string OrderNo { get; set; }
        public string Remark { get; set; }
        public int IsDisplay { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDT { get; set; }
    }
}
