//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZJ_WithdrawOrder
    {
        public string OrderNO { get; set; }
        public long UserID { get; set; }
        public Nullable<decimal> WithdrawAmount { get; set; }
        public Nullable<decimal> WithdrawCommission { get; set; }
        public Nullable<System.DateTime> WithdrawDT { get; set; }
        public string Verifier { get; set; }
        public Nullable<System.DateTime> VerifyDT { get; set; }
        public string Remitter { get; set; }
        public Nullable<System.DateTime> RemittanceDT { get; set; }
        public string Remark { get; set; }
        public int WithdrawResult { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string BankAccount { get; set; }
        public string BankName { get; set; }
        public string BankSubbranch { get; set; }
        public string BankUserName { get; set; }
        public int IsDisplay { get; set; }
        public int OrderSource { get; set; }
    
        public virtual YH_User YH_User { get; set; }
    }
}
