//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码,将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKTHMall.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THArea
    {
        public THArea()
        {
            this.THArea_lang = new HashSet<THArea_lang>();
        }
    
        public int THAreaID { get; set; }
        public int ParentID { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> AreaType { get; set; }
    
        public virtual ICollection<THArea_lang> THArea_lang { get; set; }
    }
}
